version: "3.5"
services:
  #db:
  #  hostname: db
  #  image: postgres:9.6
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=password
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - db-volume:/var/lib/postgresql/data:cached
  #  networks:
  #    - jupyter
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "10m"

  jupyter:
    image: myjupyter:latest
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    networks:
      - jupyter
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

#volumes:
#  db-volume:

networks:
  jupyter:
