version: "3.5"
services:
  pred-backend:
    image: pred-backend:latest
    ports:
      - "3001:5000"
    volumes:
      - ./backend/src:/app
    networks:
      - prediction-project
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  
  pred-frontend:
    image: pred-frontend:latest
    command: npm run start-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - prediction-project
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  db-volume:

networks:
  prediction-project:
